version: "3.9"
services:

  select20_mariadb:
    image: mariadb:10.11
    container_name: select20_mariadb
    restart: always
    volumes:
      - select20_mariadb_storage:/config/databases/
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - backend-laravel/.env
    environment:
        MYSQL_TCP_PORT: 3307
        MYSQL_UNIX_PORT: 3307=value
    ports:
      - 3307:3307
    networks:
      - select20_mysql_sec_net

  select20_phpmyadmin:
    image: phpmyadmin:5.2
    container_name: select20_phpmyadmin
    ports:
      - 8008:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=select20_mariadb
    networks:
      - select20_mysql_sec_net

networks:
  select20_mysql_sec_net:
    name: select20_mysql_sec_net

volumes:
  select20_laravel_storage:
  select20_mariadb_storage:
    


